# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nfl_game_id', models.IntegerField(blank=True, default=None)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('winning_team', models.CharField(max_length=255)),
                ('wager', models.IntegerField()),
                ('points_spread', models.IntegerField()),
                ('win', models.BooleanField(default=None)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nfl_date_id', models.IntegerField()),
                ('nfl_game_id', models.IntegerField()),
                ('home_team_abbr', models.CharField(max_length=255)),
                ('away_team_abbr', models.CharField(max_length=255)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('home_score_Q1', models.IntegerField()),
                ('home_score_Q2', models.IntegerField()),
                ('home_score_Q3', models.IntegerField()),
                ('home_score_Q4', models.IntegerField()),
                ('home_score_Q5', models.IntegerField()),
                ('away_score_Q1', models.IntegerField()),
                ('away_score_Q2', models.IntegerField()),
                ('away_score_Q3', models.IntegerField()),
                ('away_score_Q4', models.IntegerField()),
                ('away_score_Q5', models.IntegerField()),
                ('current_quarter', models.CharField(blank=True, max_length=255)),
                ('final_home_score', models.IntegerField(blank=True, default=0, null=True)),
                ('final_away_score', models.IntegerField(blank=True, default=0, null=True)),
                ('tv_channel', models.CharField(blank=True, default=None, max_length=20)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='main_app.User'),
        ),
    ]
