# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='nfl_game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
