# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190924_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='points_spread',
            field=models.FloatField(),
        ),
    ]
