# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190924_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='main_app.Game'),
        ),
    ]
