# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190926_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_coints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='win_percentage',
            field=models.FloatField(default=0),
        ),
    ]
