# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_parlaybet_parlayweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlayweek',
            name='sunday',
            field=models.DateField(default='2019-09-29'),
            preserve_default=False,
        ),
    ]
