# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_parlayweek_sunday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParlayLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commence_time', models.IntegerField()),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('home_points', models.FloatField()),
                ('away_points', models.FloatField()),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='main_app.ParlayWeek')),
            ],
        ),
    ]
