# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_parlayline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlaybet',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='game',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='nfl_game_id',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='payout',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='points_spread',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='result',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='wager',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='winning_team',
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='parlay',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parlays', to='main_app.ParlayWeek'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parlaybet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlays', to='main_app.User'),
        ),
    ]
