# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_parlayline_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlayline',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
