# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_parlayweek_winning_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlaybet',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parlaybet',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
