# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20190928_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlayline',
            name='game_id',
        ),
        migrations.AddField(
            model_name='parlayline',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parlayline', to='main_app.Game'),
        ),
    ]
