# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20190928_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlaybet',
            name='pushes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
