# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_parlaybet_pushes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlaybet',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='pushes',
        ),
        migrations.RemoveField(
            model_name='parlaybet',
            name='wins',
        ),
    ]
