# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20190928_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlaybet',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='pushes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
