# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20190928_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlaybet',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parlaybet',
            name='perfect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parlayline',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parlayweek',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
